import type { AppProps } from 'next/app';
import { createTheme, ThemeProvider, styled } from '@mui/material/styles';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import Container from '@mui/material/Container';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';
// declare module '@mui/material/styles' {
// 	interface Theme {
// 		palette: {
// 			primary: string;
// 		};
// 	}
// 	// allow configuration using `createTheme`
// 	interface ThemeOptions {
// 		palete?: {
// 			primary?: string;
// 		};
// 	}
// }

const theme = createTheme({
	palette: {
		primary: {
			main: '#574141',
		},
		secondary: {
			main: '#565C00',
		},
	},
});

export default function App({ Component, pageProps }: AppProps) {
	return (
		<ThemeProvider theme={theme}>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
				/>
			</Head>
			<Layout>
				<CssBaseline />
				<Container maxWidth='xl' className={styles.container}>
					<Component {...pageProps} />
				</Container>
			</Layout>
		</ThemeProvider>
	);
}
